# Copyright 2026 konradasb
# SPDX-License-Identifier: MIT

---
galaxy_info:
  author: konradasb
  description: Install the dicer command line from Dicer's GitHub releases.
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - dicer
    - cli
    - virtualization

dependencies: []
