# Copyright 2026 konradasb
# SPDX-License-Identifier: MIT

---
- name: Install the dicer package
  community.general.zypper:
    name: "dicer{{ '=' ~ dicerd_version if dicerd_version | length > 0 else '' }}"
    state: "{{ dicerd_package_state }}"
    oldpackage: "{{ dicerd_version | length > 0 }}"
  register: __dicerd_package
  when: not __dicerd_repository_pending
